// Roslyn Source Generator
// 빌드 시 [SyncProperty] 필드를 스캔하여 자동으로 아래를 생성:
//   - DirtyMask (uint)
//   - Serialize(NetWriter, bool) override
//   - Deserialize(NetReader, bool) override
//   - IsDirty() override
//   - ClearDirty() override
//   - 각 필드의 프로퍼티 setter에 dirty bit 주입

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MyNetEngine.SourceGen
{
    [Generator]
    public sealed class SyncPropertyGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext ctx)
        {
            ctx.RegisterForSyntaxNotifications(() => new SyncPropertySyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext ctx)
        {
            if (ctx.SyntaxReceiver is not SyncPropertySyntaxReceiver recv) return;

            var attrSymbol = ctx.Compilation.GetTypeByMetadataName("MyNetEngine.Objects.SyncPropertyAttribute");
            if (attrSymbol == null) return;

            foreach (var cls in recv.Candidates)
            {
                var model = ctx.Compilation.GetSemanticModel(cls.SyntaxTree);
                var clsSymbol = model.GetDeclaredSymbol(cls) as INamedTypeSymbol;
                if (clsSymbol == null) continue;

                var syncFields = new List<SyncFieldInfo>();
                foreach (var member in clsSymbol.GetMembers())
                {
                    if (member is not IFieldSymbol field) continue;
                    foreach (var attr in field.GetAttributes())
                    {
                        if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrSymbol)) continue;
                        byte priority = 3;
                        bool allowDelta = true;
                        int sendRate = 0;
                        foreach (var arg in attr.NamedArguments)
                        {
                            if (arg.Key == "Priority" && arg.Value.Value is byte p) priority = p;
                            if (arg.Key == "AllowDelta" && arg.Value.Value is bool d) allowDelta = d;
                            if (arg.Key == "SendRate" && arg.Value.Value is int r) sendRate = r;
                        }
                        syncFields.Add(new SyncFieldInfo
                        {
                            Name = field.Name,
                            TypeName = field.Type.ToDisplayString(),
                            Priority = priority,
                            AllowDelta = allowDelta,
                            SendRate = sendRate
                        });
                    }
                }
                if (syncFields.Count == 0) continue;
                if (syncFields.Count > 32)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("MNE001", "Too many SyncProperty fields",
                        "Max 32 [SyncProperty] fields per class (dirty mask limit). Found {0}.",
                        "MyNetEngine", DiagnosticSeverity.Error, true),
                        cls.GetLocation(), syncFields.Count));
                    continue;
                }

                string ns = clsSymbol.ContainingNamespace?.ToDisplayString() ?? "";
                string source = BuildSource(clsSymbol.Name, ns, syncFields);
                ctx.AddSource($"{clsSymbol.Name}.SyncGenerated.cs", source);
            }
        }

        private static string BuildSource(string className, string ns, List<SyncFieldInfo> fields)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> MyNetEngine SyncProperty generator");
            sb.AppendLine("using MyNetEngine.Core.Serialization;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns)) { sb.Append("namespace ").Append(ns).AppendLine(" {"); }
            sb.Append("partial class ").AppendLine(className + " {");

            // dirty mask
            sb.AppendLine("    private uint __dirtyMask;");
            sb.AppendLine("    public override bool IsDirty() => __dirtyMask != 0;");
            sb.AppendLine("    public override void ClearDirty() => __dirtyMask = 0;");

            // property wrappers (setter에 dirty set)
            for (int i = 0; i < fields.Count; i++)
            {
                var f = fields[i];
                sb.AppendLine($"    // auto-wrapper for {f.Name}");
                sb.AppendLine($"    private {f.TypeName} _{f.Name}_syncBacking;");
                sb.AppendLine($"    public {f.TypeName} Sync_{f.Name} {{");
                sb.AppendLine($"        get => _{f.Name}_syncBacking;");
                sb.AppendLine($"        set {{ if (!System.Collections.Generic.EqualityComparer<{f.TypeName}>.Default.Equals(_{f.Name}_syncBacking, value)) {{ _{f.Name}_syncBacking = value; __dirtyMask |= 1u << {i}; }} }}");
                sb.AppendLine($"    }}");
            }

            // Serialize
            sb.AppendLine("    public override void Serialize(MyNetEngine.Core.Serialization.NetWriter w, bool isInitial) {");
            sb.AppendLine("        uint mask = isInitial ? (uint)((1 << " + fields.Count + ") - 1) : __dirtyMask;");
            sb.AppendLine("        w.WriteVarUInt(mask);");
            for (int i = 0; i < fields.Count; i++)
            {
                var f = fields[i];
                sb.AppendLine($"        if ((mask & (1u << {i})) != 0) MyNetEngine.Core.Serialization.SerializerRegistry.GetWriter<{f.TypeName}>()(w, _{f.Name}_syncBacking);");
            }
            sb.AppendLine("    }");

            // Deserialize
            sb.AppendLine("    public override void Deserialize(MyNetEngine.Core.Serialization.NetReader r, bool isInitial) {");
            sb.AppendLine("        uint mask = r.ReadVarUInt();");
            for (int i = 0; i < fields.Count; i++)
            {
                var f = fields[i];
                sb.AppendLine($"        if ((mask & (1u << {i})) != 0) _{f.Name}_syncBacking = MyNetEngine.Core.Serialization.SerializerRegistry.GetReader<{f.TypeName}>() (r);");
            }
            sb.AppendLine("    }");

            sb.AppendLine("}"); // class
            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");
            return sb.ToString();
        }
    }

    internal sealed class SyncFieldInfo
    {
        public string Name;
        public string TypeName;
        public byte Priority;
        public bool AllowDelta;
        public int SendRate;
    }

    internal sealed class SyncPropertySyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();
        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0)
                Candidates.Add(cls);
        }
    }
}
